package fr.wild.hibernate;

// Generated 10 nov. 2015 15:14:18 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Approval generated by hbm2java
 */
public class Approval implements java.io.Serializable {

	private short idApproval;
	private String fullName;
	private String description;
	private Set<Drop> drops = new HashSet<Drop>(0);
	private Set<River> rivers = new HashSet<River>(0);
	private Set<CommentFile> commentFiles = new HashSet<CommentFile>(0);
	private Set<CommentDrop> commentDrops = new HashSet<CommentDrop>(0);
	private Set<Project> projects = new HashSet<Project>(0);

	public Approval() {
	}

	public Approval(short idApproval, String fullName) {
		this.idApproval = idApproval;
		this.fullName = fullName;
	}

	public Approval(short idApproval, String fullName, String description,
			Set<Drop> drops, Set<River> rivers, Set<CommentFile> commentFiles,
			Set<CommentDrop> commentDrops, Set<Project> projects) {
		this.idApproval = idApproval;
		this.fullName = fullName;
		this.description = description;
		this.drops = drops;
		this.rivers = rivers;
		this.commentFiles = commentFiles;
		this.commentDrops = commentDrops;
		this.projects = projects;
	}

	public short getIdApproval() {
		return this.idApproval;
	}

	public void setIdApproval(short idApproval) {
		this.idApproval = idApproval;
	}

	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<Drop> getDrops() {
		return this.drops;
	}

	public void setDrops(Set<Drop> drops) {
		this.drops = drops;
	}

	public Set<River> getRivers() {
		return this.rivers;
	}

	public void setRivers(Set<River> rivers) {
		this.rivers = rivers;
	}

	public Set<CommentFile> getCommentFiles() {
		return this.commentFiles;
	}

	public void setCommentFiles(Set<CommentFile> commentFiles) {
		this.commentFiles = commentFiles;
	}

	public Set<CommentDrop> getCommentDrops() {
		return this.commentDrops;
	}

	public void setCommentDrops(Set<CommentDrop> commentDrops) {
		this.commentDrops = commentDrops;
	}

	public Set<Project> getProjects() {
		return this.projects;
	}

	public void setProjects(Set<Project> projects) {
		this.projects = projects;
	}

}
