package fr.wild.hibernate;

// Generated 10 nov. 2015 15:14:18 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * CgiAbility generated by hbm2java
 */
public class CgiAbility implements java.io.Serializable {

	private String idCgiAbility;
	private String fullName;
	private String description;
	private Set<DropRightsManagement> dropRightsManagements = new HashSet<DropRightsManagement>(
			0);

	public CgiAbility() {
	}

	public CgiAbility(String idCgiAbility) {
		this.idCgiAbility = idCgiAbility;
	}

	public CgiAbility(String idCgiAbility, String fullName, String description,
			Set<DropRightsManagement> dropRightsManagements) {
		this.idCgiAbility = idCgiAbility;
		this.fullName = fullName;
		this.description = description;
		this.dropRightsManagements = dropRightsManagements;
	}

	public String getIdCgiAbility() {
		return this.idCgiAbility;
	}

	public void setIdCgiAbility(String idCgiAbility) {
		this.idCgiAbility = idCgiAbility;
	}

	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<DropRightsManagement> getDropRightsManagements() {
		return this.dropRightsManagements;
	}

	public void setDropRightsManagements(
			Set<DropRightsManagement> dropRightsManagements) {
		this.dropRightsManagements = dropRightsManagements;
	}

}
