package fr.wild.hibernate;

// Generated 10 nov. 2015 15:14:18 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * CgiItem generated by hbm2java
 */
public class CgiItem implements java.io.Serializable {

	private String idCgiItem;
	private String fullName;
	private String description;
	private Set<Drop> drops = new HashSet<Drop>(0);
	private Set<DropRightsManagement> dropRightsManagements = new HashSet<DropRightsManagement>(
			0);

	public CgiItem() {
	}

	public CgiItem(String idCgiItem, String fullName) {
		this.idCgiItem = idCgiItem;
		this.fullName = fullName;
	}

	public CgiItem(String idCgiItem, String fullName, String description,
			Set<Drop> drops, Set<DropRightsManagement> dropRightsManagements) {
		this.idCgiItem = idCgiItem;
		this.fullName = fullName;
		this.description = description;
		this.drops = drops;
		this.dropRightsManagements = dropRightsManagements;
	}

	public String getIdCgiItem() {
		return this.idCgiItem;
	}

	public void setIdCgiItem(String idCgiItem) {
		this.idCgiItem = idCgiItem;
	}

	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<Drop> getDrops() {
		return this.drops;
	}

	public void setDrops(Set<Drop> drops) {
		this.drops = drops;
	}

	public Set<DropRightsManagement> getDropRightsManagements() {
		return this.dropRightsManagements;
	}

	public void setDropRightsManagements(
			Set<DropRightsManagement> dropRightsManagements) {
		this.dropRightsManagements = dropRightsManagements;
	}

}
