package fr.wild.hibernate;

// Generated 10 nov. 2015 15:14:18 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Criticity generated by hbm2java
 */
public class Criticity implements java.io.Serializable {

	private short idCriticity;
	private String fullName;
	private String description;
	private Set<ExecutionInfo> executionInfos = new HashSet<ExecutionInfo>(0);
	private Set<JavaServiceInfo> javaServiceInfos = new HashSet<JavaServiceInfo>(
			0);

	public Criticity() {
	}

	public Criticity(short idCriticity, String fullName) {
		this.idCriticity = idCriticity;
		this.fullName = fullName;
	}

	public Criticity(short idCriticity, String fullName, String description,
			Set<ExecutionInfo> executionInfos,
			Set<JavaServiceInfo> javaServiceInfos) {
		this.idCriticity = idCriticity;
		this.fullName = fullName;
		this.description = description;
		this.executionInfos = executionInfos;
		this.javaServiceInfos = javaServiceInfos;
	}

	public short getIdCriticity() {
		return this.idCriticity;
	}

	public void setIdCriticity(short idCriticity) {
		this.idCriticity = idCriticity;
	}

	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<ExecutionInfo> getExecutionInfos() {
		return this.executionInfos;
	}

	public void setExecutionInfos(Set<ExecutionInfo> executionInfos) {
		this.executionInfos = executionInfos;
	}

	public Set<JavaServiceInfo> getJavaServiceInfos() {
		return this.javaServiceInfos;
	}

	public void setJavaServiceInfos(Set<JavaServiceInfo> javaServiceInfos) {
		this.javaServiceInfos = javaServiceInfos;
	}

}
