package fr.wild.hibernate;

// Generated 10 nov. 2015 15:14:18 by Hibernate Tools 3.4.0.CR1

/**
 * DropRightsManagement generated by hbm2java
 */
public class DropRightsManagement implements java.io.Serializable {

	private DropRightsManagementId id;
	private CgiAbility cgiAbility;
	private CgiItem cgiItem;
	private AdminLevel adminLevel;

	public DropRightsManagement() {
	}

	public DropRightsManagement(DropRightsManagementId id,
			CgiAbility cgiAbility, CgiItem cgiItem, AdminLevel adminLevel) {
		this.id = id;
		this.cgiAbility = cgiAbility;
		this.cgiItem = cgiItem;
		this.adminLevel = adminLevel;
	}

	public DropRightsManagementId getId() {
		return this.id;
	}

	public void setId(DropRightsManagementId id) {
		this.id = id;
	}

	public CgiAbility getCgiAbility() {
		return this.cgiAbility;
	}

	public void setCgiAbility(CgiAbility cgiAbility) {
		this.cgiAbility = cgiAbility;
	}

	public CgiItem getCgiItem() {
		return this.cgiItem;
	}

	public void setCgiItem(CgiItem cgiItem) {
		this.cgiItem = cgiItem;
	}

	public AdminLevel getAdminLevel() {
		return this.adminLevel;
	}

	public void setAdminLevel(AdminLevel adminLevel) {
		this.adminLevel = adminLevel;
	}

}
