package fr.wild.hibernate;

// Generated 10 nov. 2015 15:14:18 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Drop generated by hbm2java
 */
public class Drop implements java.io.Serializable {

	private String idDrop;
	private Project project;
	private CgiItem cgiItem;
	private User user;
	private River river;
	private Approval approval;
	private Date dateCreation;
	private Date dateLastModif;
	private String contents;
	private String tags;
	private Set<CommentDrop> commentDrops = new HashSet<CommentDrop>(0);

	public Drop() {
	}

	public Drop(String idDrop, User user, Approval approval, Date dateCreation) {
		this.idDrop = idDrop;
		this.user = user;
		this.approval = approval;
		this.dateCreation = dateCreation;
	}

	public Drop(String idDrop, Project project, CgiItem cgiItem, User user,
			River river, Approval approval, Date dateCreation,
			Date dateLastModif, String contents, String tags,
			Set<CommentDrop> commentDrops) {
		this.idDrop = idDrop;
		this.project = project;
		this.cgiItem = cgiItem;
		this.user = user;
		this.river = river;
		this.approval = approval;
		this.dateCreation = dateCreation;
		this.dateLastModif = dateLastModif;
		this.contents = contents;
		this.tags = tags;
		this.commentDrops = commentDrops;
	}

	public String getIdDrop() {
		return this.idDrop;
	}

	public void setIdDrop(String idDrop) {
		this.idDrop = idDrop;
	}

	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	public CgiItem getCgiItem() {
		return this.cgiItem;
	}

	public void setCgiItem(CgiItem cgiItem) {
		this.cgiItem = cgiItem;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public River getRiver() {
		return this.river;
	}

	public void setRiver(River river) {
		this.river = river;
	}

	public Approval getApproval() {
		return this.approval;
	}

	public void setApproval(Approval approval) {
		this.approval = approval;
	}

	public Date getDateCreation() {
		return this.dateCreation;
	}

	public void setDateCreation(Date dateCreation) {
		this.dateCreation = dateCreation;
	}

	public Date getDateLastModif() {
		return this.dateLastModif;
	}

	public void setDateLastModif(Date dateLastModif) {
		this.dateLastModif = dateLastModif;
	}

	public String getContents() {
		return this.contents;
	}

	public void setContents(String contents) {
		this.contents = contents;
	}

	public String getTags() {
		return this.tags;
	}

	public void setTags(String tags) {
		this.tags = tags;
	}

	public Set<CommentDrop> getCommentDrops() {
		return this.commentDrops;
	}

	public void setCommentDrops(Set<CommentDrop> commentDrops) {
		this.commentDrops = commentDrops;
	}

}
