package fr.wild.hibernate;

// Generated 10 nov. 2015 15:14:18 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * ExecutionInfo generated by hbm2java
 */
public class ExecutionInfo implements java.io.Serializable {

	private long idExecutionInfo;
	private ExecutionList executionList;
	private AdminLevel adminLevel;
	private Criticity criticity;
	private Date dateMessage;
	private String contents;

	public ExecutionInfo() {
	}

	public ExecutionInfo(long idExecutionInfo, ExecutionList executionList,
			AdminLevel adminLevel, Criticity criticity, Date dateMessage) {
		this.idExecutionInfo = idExecutionInfo;
		this.executionList = executionList;
		this.adminLevel = adminLevel;
		this.criticity = criticity;
		this.dateMessage = dateMessage;
	}

	public ExecutionInfo(long idExecutionInfo, ExecutionList executionList,
			AdminLevel adminLevel, Criticity criticity, Date dateMessage,
			String contents) {
		this.idExecutionInfo = idExecutionInfo;
		this.executionList = executionList;
		this.adminLevel = adminLevel;
		this.criticity = criticity;
		this.dateMessage = dateMessage;
		this.contents = contents;
	}

	public long getIdExecutionInfo() {
		return this.idExecutionInfo;
	}

	public void setIdExecutionInfo(long idExecutionInfo) {
		this.idExecutionInfo = idExecutionInfo;
	}

	public ExecutionList getExecutionList() {
		return this.executionList;
	}

	public void setExecutionList(ExecutionList executionList) {
		this.executionList = executionList;
	}

	public AdminLevel getAdminLevel() {
		return this.adminLevel;
	}

	public void setAdminLevel(AdminLevel adminLevel) {
		this.adminLevel = adminLevel;
	}

	public Criticity getCriticity() {
		return this.criticity;
	}

	public void setCriticity(Criticity criticity) {
		this.criticity = criticity;
	}

	public Date getDateMessage() {
		return this.dateMessage;
	}

	public void setDateMessage(Date dateMessage) {
		this.dateMessage = dateMessage;
	}

	public String getContents() {
		return this.contents;
	}

	public void setContents(String contents) {
		this.contents = contents;
	}

}
