package fr.wild.hibernate;

// Generated 10 nov. 2015 15:14:18 by Hibernate Tools 3.4.0.CR1

/**
 * ExecutionConsumption generated by hbm2java
 */
public class ExecutionConsumption implements java.io.Serializable {

	private String idExecution;
	private ExecutionList executionList;
	private Integer maxAllocatedRom;
	private Integer maxAllocatedRam;
	private Integer maxAllocatedCpu;
	private Integer estimatedRom;
	private Integer estimatedRam;
	private Integer estimatedCpu;

	public ExecutionConsumption() {
	}

	public ExecutionConsumption(ExecutionList executionList) {
		this.executionList = executionList;
	}

	public ExecutionConsumption(ExecutionList executionList,
			Integer maxAllocatedRom, Integer maxAllocatedRam,
			Integer maxAllocatedCpu, Integer estimatedRom,
			Integer estimatedRam, Integer estimatedCpu) {
		this.executionList = executionList;
		this.maxAllocatedRom = maxAllocatedRom;
		this.maxAllocatedRam = maxAllocatedRam;
		this.maxAllocatedCpu = maxAllocatedCpu;
		this.estimatedRom = estimatedRom;
		this.estimatedRam = estimatedRam;
		this.estimatedCpu = estimatedCpu;
	}

	public String getIdExecution() {
		return this.idExecution;
	}

	public void setIdExecution(String idExecution) {
		this.idExecution = idExecution;
	}

	public ExecutionList getExecutionList() {
		return this.executionList;
	}

	public void setExecutionList(ExecutionList executionList) {
		this.executionList = executionList;
	}

	public Integer getMaxAllocatedRom() {
		return this.maxAllocatedRom;
	}

	public void setMaxAllocatedRom(Integer maxAllocatedRom) {
		this.maxAllocatedRom = maxAllocatedRom;
	}

	public Integer getMaxAllocatedRam() {
		return this.maxAllocatedRam;
	}

	public void setMaxAllocatedRam(Integer maxAllocatedRam) {
		this.maxAllocatedRam = maxAllocatedRam;
	}

	public Integer getMaxAllocatedCpu() {
		return this.maxAllocatedCpu;
	}

	public void setMaxAllocatedCpu(Integer maxAllocatedCpu) {
		this.maxAllocatedCpu = maxAllocatedCpu;
	}

	public Integer getEstimatedRom() {
		return this.estimatedRom;
	}

	public void setEstimatedRom(Integer estimatedRom) {
		this.estimatedRom = estimatedRom;
	}

	public Integer getEstimatedRam() {
		return this.estimatedRam;
	}

	public void setEstimatedRam(Integer estimatedRam) {
		this.estimatedRam = estimatedRam;
	}

	public Integer getEstimatedCpu() {
		return this.estimatedCpu;
	}

	public void setEstimatedCpu(Integer estimatedCpu) {
		this.estimatedCpu = estimatedCpu;
	}

}
