package fr.wild.hibernate;

// Generated 10 nov. 2015 15:14:18 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * ExecutionChainsaw generated by hbm2java
 */
public class ExecutionChainsaw implements java.io.Serializable {

	private String idExecution;
	private JavaService javaService;
	private User user;
	private ExecutionList executionList;
	private Status status;
	private Date datePost;
	private Boolean withMail;
	private Date dateBegin;
	private Date dateEnd;
	private String infoIn;
	private String infoOut;
	private Integer maxAllocatedRom;
	private Integer maxAllocatedRam;
	private Integer maxAllocatedCpu;
	private Integer estimatedRom;
	private Integer estimatedRam;
	private Integer estimatedCpu;
	private Boolean stepVisible;

	public ExecutionChainsaw() {
	}

	public ExecutionChainsaw(User user, ExecutionList executionList,
			Date datePost) {
		this.user = user;
		this.executionList = executionList;
		this.datePost = datePost;
	}

	public ExecutionChainsaw(JavaService javaService, User user,
			ExecutionList executionList, Status status, Date datePost,
			Boolean withMail, Date dateBegin, Date dateEnd, String infoIn,
			String infoOut, Integer maxAllocatedRom, Integer maxAllocatedRam,
			Integer maxAllocatedCpu, Integer estimatedRom,
			Integer estimatedRam, Integer estimatedCpu, Boolean stepVisible) {
		this.javaService = javaService;
		this.user = user;
		this.executionList = executionList;
		this.status = status;
		this.datePost = datePost;
		this.withMail = withMail;
		this.dateBegin = dateBegin;
		this.dateEnd = dateEnd;
		this.infoIn = infoIn;
		this.infoOut = infoOut;
		this.maxAllocatedRom = maxAllocatedRom;
		this.maxAllocatedRam = maxAllocatedRam;
		this.maxAllocatedCpu = maxAllocatedCpu;
		this.estimatedRom = estimatedRom;
		this.estimatedRam = estimatedRam;
		this.estimatedCpu = estimatedCpu;
		this.stepVisible = stepVisible;
	}

	public String getIdExecution() {
		return this.idExecution;
	}

	public void setIdExecution(String idExecution) {
		this.idExecution = idExecution;
	}

	public JavaService getJavaService() {
		return this.javaService;
	}

	public void setJavaService(JavaService javaService) {
		this.javaService = javaService;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public ExecutionList getExecutionList() {
		return this.executionList;
	}

	public void setExecutionList(ExecutionList executionList) {
		this.executionList = executionList;
	}

	public Status getStatus() {
		return this.status;
	}

	public void setStatus(Status status) {
		this.status = status;
	}

	public Date getDatePost() {
		return this.datePost;
	}

	public void setDatePost(Date datePost) {
		this.datePost = datePost;
	}

	public Boolean getWithMail() {
		return this.withMail;
	}

	public void setWithMail(Boolean withMail) {
		this.withMail = withMail;
	}

	public Date getDateBegin() {
		return this.dateBegin;
	}

	public void setDateBegin(Date dateBegin) {
		this.dateBegin = dateBegin;
	}

	public Date getDateEnd() {
		return this.dateEnd;
	}

	public void setDateEnd(Date dateEnd) {
		this.dateEnd = dateEnd;
	}

	public String getInfoIn() {
		return this.infoIn;
	}

	public void setInfoIn(String infoIn) {
		this.infoIn = infoIn;
	}

	public String getInfoOut() {
		return this.infoOut;
	}

	public void setInfoOut(String infoOut) {
		this.infoOut = infoOut;
	}

	public Integer getMaxAllocatedRom() {
		return this.maxAllocatedRom;
	}

	public void setMaxAllocatedRom(Integer maxAllocatedRom) {
		this.maxAllocatedRom = maxAllocatedRom;
	}

	public Integer getMaxAllocatedRam() {
		return this.maxAllocatedRam;
	}

	public void setMaxAllocatedRam(Integer maxAllocatedRam) {
		this.maxAllocatedRam = maxAllocatedRam;
	}

	public Integer getMaxAllocatedCpu() {
		return this.maxAllocatedCpu;
	}

	public void setMaxAllocatedCpu(Integer maxAllocatedCpu) {
		this.maxAllocatedCpu = maxAllocatedCpu;
	}

	public Integer getEstimatedRom() {
		return this.estimatedRom;
	}

	public void setEstimatedRom(Integer estimatedRom) {
		this.estimatedRom = estimatedRom;
	}

	public Integer getEstimatedRam() {
		return this.estimatedRam;
	}

	public void setEstimatedRam(Integer estimatedRam) {
		this.estimatedRam = estimatedRam;
	}

	public Integer getEstimatedCpu() {
		return this.estimatedCpu;
	}

	public void setEstimatedCpu(Integer estimatedCpu) {
		this.estimatedCpu = estimatedCpu;
	}

	public Boolean getStepVisible() {
		return this.stepVisible;
	}

	public void setStepVisible(Boolean stepVisible) {
		this.stepVisible = stepVisible;
	}

}
