package fr.wild.hibernate;

// Generated 10 nov. 2015 15:14:18 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * ExecutionList generated by hbm2java
 */
public class ExecutionList implements java.io.Serializable {

	private String idExecution;
	private JavaService javaService;
	private User user;
	private Status status;
	private ExecutionArchive executionArchive;
	private ExecutionChainsaw executionChainsaw;
	private ExecutionConsumption executionConsumption;
	private Set<ExecutionInfo> executionInfos = new HashSet<ExecutionInfo>(0);

	public ExecutionList() {
	}

	public ExecutionList(String idExecution, User user) {
		this.idExecution = idExecution;
		this.user = user;
	}

	public ExecutionList(String idExecution, JavaService javaService,
			User user, Status status, ExecutionArchive executionArchive,
			ExecutionChainsaw executionChainsaw,
			ExecutionConsumption executionConsumption,
			Set<ExecutionInfo> executionInfos) {
		this.idExecution = idExecution;
		this.javaService = javaService;
		this.user = user;
		this.status = status;
		this.executionArchive = executionArchive;
		this.executionChainsaw = executionChainsaw;
		this.executionConsumption = executionConsumption;
		this.executionInfos = executionInfos;
	}

	public String getIdExecution() {
		return this.idExecution;
	}

	public void setIdExecution(String idExecution) {
		this.idExecution = idExecution;
	}

	public JavaService getJavaService() {
		return this.javaService;
	}

	public void setJavaService(JavaService javaService) {
		this.javaService = javaService;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Status getStatus() {
		return this.status;
	}

	public void setStatus(Status status) {
		this.status = status;
	}

	public ExecutionArchive getExecutionArchive() {
		return this.executionArchive;
	}

	public void setExecutionArchive(ExecutionArchive executionArchive) {
		this.executionArchive = executionArchive;
	}

	public ExecutionChainsaw getExecutionChainsaw() {
		return this.executionChainsaw;
	}

	public void setExecutionChainsaw(ExecutionChainsaw executionChainsaw) {
		this.executionChainsaw = executionChainsaw;
	}

	public ExecutionConsumption getExecutionConsumption() {
		return this.executionConsumption;
	}

	public void setExecutionConsumption(
			ExecutionConsumption executionConsumption) {
		this.executionConsumption = executionConsumption;
	}

	public Set<ExecutionInfo> getExecutionInfos() {
		return this.executionInfos;
	}

	public void setExecutionInfos(Set<ExecutionInfo> executionInfos) {
		this.executionInfos = executionInfos;
	}

}
