package fr.wild.hibernate;

// Generated 10 nov. 2015 15:14:18 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;

/**
 * ExecutionArchive generated by hbm2java
 */
public class ExecutionArchive implements java.io.Serializable {

	private String idExecution;
	private JavaService javaService;
	private User user;
	private ExecutionList executionList;
	private Status status;
	private String products;
	private String scenarioName;
	private String infoOut;
	private String summary;
	private Date datePost;
	private Date dateBegin;
	private Date dateEnd;
	private Date dateArchive;
	private Date dateConsult;
	private Date dateMail;

	public ExecutionArchive() {
	}

	public ExecutionArchive(User user, ExecutionList executionList,
			String scenarioName, Date datePost, Date dateArchive) {
		this.user = user;
		this.executionList = executionList;
		this.scenarioName = scenarioName;
		this.datePost = datePost;
		this.dateArchive = dateArchive;
	}

	public ExecutionArchive(JavaService javaService, User user,
			ExecutionList executionList, Status status, String products,
			String scenarioName, String infoOut, String summary, Date datePost,
			Date dateBegin, Date dateEnd, Date dateArchive, Date dateConsult,
			Date dateMail) {
		this.javaService = javaService;
		this.user = user;
		this.executionList = executionList;
		this.status = status;
		this.products = products;
		this.scenarioName = scenarioName;
		this.infoOut = infoOut;
		this.summary = summary;
		this.datePost = datePost;
		this.dateBegin = dateBegin;
		this.dateEnd = dateEnd;
		this.dateArchive = dateArchive;
		this.dateConsult = dateConsult;
		this.dateMail = dateMail;
	}

	public String getIdExecution() {
		return this.idExecution;
	}

	public void setIdExecution(String idExecution) {
		this.idExecution = idExecution;
	}

	public JavaService getJavaService() {
		return this.javaService;
	}

	public void setJavaService(JavaService javaService) {
		this.javaService = javaService;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public ExecutionList getExecutionList() {
		return this.executionList;
	}

	public void setExecutionList(ExecutionList executionList) {
		this.executionList = executionList;
	}

	public Status getStatus() {
		return this.status;
	}

	public void setStatus(Status status) {
		this.status = status;
	}

	public String getProducts() {
		return this.products;
	}

	public void setProducts(String products) {
		this.products = products;
	}

	public String getScenarioName() {
		return this.scenarioName;
	}

	public void setScenarioName(String scenarioName) {
		this.scenarioName = scenarioName;
	}

	public String getInfoOut() {
		return this.infoOut;
	}

	public void setInfoOut(String infoOut) {
		this.infoOut = infoOut;
	}

	public String getSummary() {
		return this.summary;
	}

	public void setSummary(String summary) {
		this.summary = summary;
	}

	public Date getDatePost() {
		return this.datePost;
	}

	public void setDatePost(Date datePost) {
		this.datePost = datePost;
	}

	public Date getDateBegin() {
		return this.dateBegin;
	}

	public void setDateBegin(Date dateBegin) {
		this.dateBegin = dateBegin;
	}

	public Date getDateEnd() {
		return this.dateEnd;
	}

	public void setDateEnd(Date dateEnd) {
		this.dateEnd = dateEnd;
	}

	public Date getDateArchive() {
		return this.dateArchive;
	}

	public void setDateArchive(Date dateArchive) {
		this.dateArchive = dateArchive;
	}

	public Date getDateConsult() {
		return this.dateConsult;
	}

	public void setDateConsult(Date dateConsult) {
		this.dateConsult = dateConsult;
	}

	public Date getDateMail() {
		return this.dateMail;
	}

	public void setDateMail(Date dateMail) {
		this.dateMail = dateMail;
	}

}
