package fr.wild.hibernate;

// Generated 10 nov. 2015 15:14:18 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * JavaService generated by hbm2java
 */
public class JavaService implements java.io.Serializable {

	private String idJavaservice;
	private User user;
	private Status status;
	private Date dateBegin;
	private Date dateEnd;
	private String infoOut;
	private Set<ExecutionList> executionLists = new HashSet<ExecutionList>(0);
	private Set<JavaConsumption> javaConsumptions = new HashSet<JavaConsumption>(
			0);
	private Set<ExecutionChainsaw> executionChainsaws = new HashSet<ExecutionChainsaw>(
			0);
	private Set<JavaServiceInfo> javaServiceInfos = new HashSet<JavaServiceInfo>(
			0);
	private Set<ExecutionArchive> executionArchives = new HashSet<ExecutionArchive>(
			0);

	public JavaService() {
	}

	public JavaService(String idJavaservice, User user, Date dateBegin) {
		this.idJavaservice = idJavaservice;
		this.user = user;
		this.dateBegin = dateBegin;
	}

	public JavaService(String idJavaservice, User user, Status status,
			Date dateBegin, Date dateEnd, String infoOut,
			Set<ExecutionList> executionLists,
			Set<JavaConsumption> javaConsumptions,
			Set<ExecutionChainsaw> executionChainsaws,
			Set<JavaServiceInfo> javaServiceInfos,
			Set<ExecutionArchive> executionArchives) {
		this.idJavaservice = idJavaservice;
		this.user = user;
		this.status = status;
		this.dateBegin = dateBegin;
		this.dateEnd = dateEnd;
		this.infoOut = infoOut;
		this.executionLists = executionLists;
		this.javaConsumptions = javaConsumptions;
		this.executionChainsaws = executionChainsaws;
		this.javaServiceInfos = javaServiceInfos;
		this.executionArchives = executionArchives;
	}

	public String getIdJavaservice() {
		return this.idJavaservice;
	}

	public void setIdJavaservice(String idJavaservice) {
		this.idJavaservice = idJavaservice;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Status getStatus() {
		return this.status;
	}

	public void setStatus(Status status) {
		this.status = status;
	}

	public Date getDateBegin() {
		return this.dateBegin;
	}

	public void setDateBegin(Date dateBegin) {
		this.dateBegin = dateBegin;
	}

	public Date getDateEnd() {
		return this.dateEnd;
	}

	public void setDateEnd(Date dateEnd) {
		this.dateEnd = dateEnd;
	}

	public String getInfoOut() {
		return this.infoOut;
	}

	public void setInfoOut(String infoOut) {
		this.infoOut = infoOut;
	}

	public Set<ExecutionList> getExecutionLists() {
		return this.executionLists;
	}

	public void setExecutionLists(Set<ExecutionList> executionLists) {
		this.executionLists = executionLists;
	}

	public Set<JavaConsumption> getJavaConsumptions() {
		return this.javaConsumptions;
	}

	public void setJavaConsumptions(Set<JavaConsumption> javaConsumptions) {
		this.javaConsumptions = javaConsumptions;
	}

	public Set<ExecutionChainsaw> getExecutionChainsaws() {
		return this.executionChainsaws;
	}

	public void setExecutionChainsaws(Set<ExecutionChainsaw> executionChainsaws) {
		this.executionChainsaws = executionChainsaws;
	}

	public Set<JavaServiceInfo> getJavaServiceInfos() {
		return this.javaServiceInfos;
	}

	public void setJavaServiceInfos(Set<JavaServiceInfo> javaServiceInfos) {
		this.javaServiceInfos = javaServiceInfos;
	}

	public Set<ExecutionArchive> getExecutionArchives() {
		return this.executionArchives;
	}

	public void setExecutionArchives(Set<ExecutionArchive> executionArchives) {
		this.executionArchives = executionArchives;
	}

}
