package fr.wild.hibernate;

// Generated 10 nov. 2015 15:14:18 by Hibernate Tools 3.4.0.CR1

/**
 * JavaConsumption generated by hbm2java
 */
public class JavaConsumption implements java.io.Serializable {

	private JavaConsumptionId id;
	private JavaService javaService;
	private Integer maxAllocatedRom;
	private Integer maxAllocatedRam;
	private Integer maxAllocatedCpu;
	private Integer estimatedRom;
	private Integer estimatedRam;
	private Integer estimatedCpu;
	private Integer executionCt;

	public JavaConsumption() {
	}

	public JavaConsumption(JavaConsumptionId id, JavaService javaService) {
		this.id = id;
		this.javaService = javaService;
	}

	public JavaConsumption(JavaConsumptionId id, JavaService javaService,
			Integer maxAllocatedRom, Integer maxAllocatedRam,
			Integer maxAllocatedCpu, Integer estimatedRom,
			Integer estimatedRam, Integer estimatedCpu, Integer executionCt) {
		this.id = id;
		this.javaService = javaService;
		this.maxAllocatedRom = maxAllocatedRom;
		this.maxAllocatedRam = maxAllocatedRam;
		this.maxAllocatedCpu = maxAllocatedCpu;
		this.estimatedRom = estimatedRom;
		this.estimatedRam = estimatedRam;
		this.estimatedCpu = estimatedCpu;
		this.executionCt = executionCt;
	}

	public JavaConsumptionId getId() {
		return this.id;
	}

	public void setId(JavaConsumptionId id) {
		this.id = id;
	}

	public JavaService getJavaService() {
		return this.javaService;
	}

	public void setJavaService(JavaService javaService) {
		this.javaService = javaService;
	}

	public Integer getMaxAllocatedRom() {
		return this.maxAllocatedRom;
	}

	public void setMaxAllocatedRom(Integer maxAllocatedRom) {
		this.maxAllocatedRom = maxAllocatedRom;
	}

	public Integer getMaxAllocatedRam() {
		return this.maxAllocatedRam;
	}

	public void setMaxAllocatedRam(Integer maxAllocatedRam) {
		this.maxAllocatedRam = maxAllocatedRam;
	}

	public Integer getMaxAllocatedCpu() {
		return this.maxAllocatedCpu;
	}

	public void setMaxAllocatedCpu(Integer maxAllocatedCpu) {
		this.maxAllocatedCpu = maxAllocatedCpu;
	}

	public Integer getEstimatedRom() {
		return this.estimatedRom;
	}

	public void setEstimatedRom(Integer estimatedRom) {
		this.estimatedRom = estimatedRom;
	}

	public Integer getEstimatedRam() {
		return this.estimatedRam;
	}

	public void setEstimatedRam(Integer estimatedRam) {
		this.estimatedRam = estimatedRam;
	}

	public Integer getEstimatedCpu() {
		return this.estimatedCpu;
	}

	public void setEstimatedCpu(Integer estimatedCpu) {
		this.estimatedCpu = estimatedCpu;
	}

	public Integer getExecutionCt() {
		return this.executionCt;
	}

	public void setExecutionCt(Integer executionCt) {
		this.executionCt = executionCt;
	}

}
