package fr.wild.hibernate;

// Generated 10 nov. 2015 15:14:18 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * JavaConsumptionId generated by hbm2java
 */
public class JavaConsumptionId implements java.io.Serializable {

	private Date dateInfo;
	private String idJavaservice;

	public JavaConsumptionId() {
	}

	public JavaConsumptionId(Date dateInfo, String idJavaservice) {
		this.dateInfo = dateInfo;
		this.idJavaservice = idJavaservice;
	}

	public Date getDateInfo() {
		return this.dateInfo;
	}

	public void setDateInfo(Date dateInfo) {
		this.dateInfo = dateInfo;
	}

	public String getIdJavaservice() {
		return this.idJavaservice;
	}

	public void setIdJavaservice(String idJavaservice) {
		this.idJavaservice = idJavaservice;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof JavaConsumptionId))
			return false;
		JavaConsumptionId castOther = (JavaConsumptionId) other;

		return ((this.getDateInfo() == castOther.getDateInfo()) || (this
				.getDateInfo() != null && castOther.getDateInfo() != null && this
				.getDateInfo().equals(castOther.getDateInfo())))
				&& ((this.getIdJavaservice() == castOther.getIdJavaservice()) || (this
						.getIdJavaservice() != null
						&& castOther.getIdJavaservice() != null && this
						.getIdJavaservice()
						.equals(castOther.getIdJavaservice())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getDateInfo() == null ? 0 : this.getDateInfo().hashCode());
		result = 37
				* result
				+ (getIdJavaservice() == null ? 0 : this.getIdJavaservice()
						.hashCode());
		return result;
	}

}
