package fr.wild.hibernate;

// Generated 16 nov. 2015 18:21:27 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Model generated by hbm2java
 */
public class Model implements java.io.Serializable {

	private int idModel;
	private String version;
	private Date dateCreation;
	private String codeVersion;
	private String shortName;
	private String fullName;
	private String description;
	private String jarName;
	private Boolean favorite;
	
	private Set<ModelsExecution> modelsExecutions = new HashSet<ModelsExecution>(
			0);

	public Model() {
	}

	public Model(int idModel, Date dateCreation, String codeVersion,
			String shortName, String fullName) {
		this.idModel = idModel;
		this.dateCreation = dateCreation;
		this.codeVersion = codeVersion;
		this.shortName = shortName;
		this.fullName = fullName;
	}

	public Model(int idModel, Date dateCreation, String codeVersion,
			String shortName, String fullName, String description,
			Set<ModelsExecution> modelsExecutions) {
		this.idModel = idModel;
		this.dateCreation = dateCreation;
		this.codeVersion = codeVersion;
		this.shortName = shortName;
		this.fullName = fullName;
		this.description = description;
		this.modelsExecutions = modelsExecutions;
	}

	public int getIdModel() {
		return this.idModel;
	}

	public void setIdModel(int idModel) {
		this.idModel = idModel;
	}

	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	public Date getDateCreation() {
		return this.dateCreation;
	}

	public void setDateCreation(Date dateCreation) {
		this.dateCreation = dateCreation;
	}

	public String getCodeVersion() {
		return this.codeVersion;
	}

	public void setCodeVersion(String codeVersion) {
		this.codeVersion = codeVersion;
	}

	public String getShortName() {
		return this.shortName;
	}

	public void setShortName(String shortName) {
		this.shortName = shortName;
	}

	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<ModelsExecution> getModelsExecutions() {
		return this.modelsExecutions;
	}

	public void setModelsExecutions(Set<ModelsExecution> modelsExecutions) {
		this.modelsExecutions = modelsExecutions;
	}

	public Boolean getFavorite() {
		return favorite;
	}

	public void setFavorite(Boolean favorite) {
		this.favorite = favorite;
	}

	public String getJarName() {
		return jarName;
	}

	public void setJarName(String jarName) {
		this.jarName = jarName;
	}

}
