package fr.wild.hibernate;

// Generated 16 nov. 2015 18:21:27 by Hibernate Tools 3.4.0.CR1

/**
 * ModelsExecutionId generated by hbm2java
 */
public class ModelsExecutionId implements java.io.Serializable {

	private Long idModel;
	private String idExecution;

	public ModelsExecutionId() {
	}

	public ModelsExecutionId(Long idModel, String idExecution) {
		this.idModel = idModel;
		this.idExecution = idExecution;
	}

	public Long getIdModel() {
		return this.idModel;
	}

	public void setIdModel(Long idModel) {
		this.idModel = idModel;
	}

	public String getIdExecution() {
		return this.idExecution;
	}

	public void setIdExecution(String idExecution) {
		this.idExecution = idExecution;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ModelsExecutionId))
			return false;
		ModelsExecutionId castOther = (ModelsExecutionId) other;

		return ((this.getIdModel() == castOther.getIdModel()) || (this
				.getIdModel() != null && castOther.getIdModel() != null && this
				.getIdModel().equals(castOther.getIdModel())))
				&& ((this.getIdExecution() == castOther.getIdExecution()) || (this
						.getIdExecution() != null
						&& castOther.getIdExecution() != null && this
						.getIdExecution().equals(castOther.getIdExecution())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getIdModel() == null ? 0 : this.getIdModel().hashCode());
		result = 37
				* result
				+ (getIdExecution() == null ? 0 : this.getIdExecution()
						.hashCode());
		return result;
	}

}
