package fr.wild.hibernate;

// Generated 10 nov. 2015 15:14:18 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Preference generated by hbm2java
 */
public class Preference implements java.io.Serializable {

	private int idPreference;
	private VarType varType;
	private AdminLevel adminLevel;
	private PreferencesGroup preferencesGroup;
	private String preferenceName;
	private String preferenceDescription;
	private String defaultValue;
	private String availablesValues;
	private Boolean activated;
	private Set<UsersPreference> usersPreferences = new HashSet<UsersPreference>(
			0);

	public Preference() {
	}

	public Preference(int idPreference, String preferenceName) {
		this.idPreference = idPreference;
		this.preferenceName = preferenceName;
	}

	public Preference(int idPreference, VarType varType, AdminLevel adminLevel,
			PreferencesGroup preferencesGroup, String preferenceName,
			String preferenceDescription, String defaultValue,
			String availablesValues, Boolean activated,
			Set<UsersPreference> usersPreferences) {
		this.idPreference = idPreference;
		this.varType = varType;
		this.adminLevel = adminLevel;
		this.preferencesGroup = preferencesGroup;
		this.preferenceName = preferenceName;
		this.preferenceDescription = preferenceDescription;
		this.defaultValue = defaultValue;
		this.availablesValues = availablesValues;
		this.activated = activated;
		this.usersPreferences = usersPreferences;
	}

	public int getIdPreference() {
		return this.idPreference;
	}

	public void setIdPreference(int idPreference) {
		this.idPreference = idPreference;
	}

	public VarType getVarType() {
		return this.varType;
	}

	public void setVarType(VarType varType) {
		this.varType = varType;
	}

	public AdminLevel getAdminLevel() {
		return this.adminLevel;
	}

	public void setAdminLevel(AdminLevel adminLevel) {
		this.adminLevel = adminLevel;
	}

	public PreferencesGroup getPreferencesGroup() {
		return this.preferencesGroup;
	}

	public void setPreferencesGroup(PreferencesGroup preferencesGroup) {
		this.preferencesGroup = preferencesGroup;
	}

	public String getPreferenceName() {
		return this.preferenceName;
	}

	public void setPreferenceName(String preferenceName) {
		this.preferenceName = preferenceName;
	}

	public String getPreferenceDescription() {
		return this.preferenceDescription;
	}

	public void setPreferenceDescription(String preferenceDescription) {
		this.preferenceDescription = preferenceDescription;
	}

	public String getDefaultValue() {
		return this.defaultValue;
	}

	public void setDefaultValue(String defaultValue) {
		this.defaultValue = defaultValue;
	}

	public String getAvailablesValues() {
		return this.availablesValues;
	}

	public void setAvailablesValues(String availablesValues) {
		this.availablesValues = availablesValues;
	}

	public Boolean getActivated() {
		return this.activated;
	}

	public void setActivated(Boolean activated) {
		this.activated = activated;
	}

	public Set<UsersPreference> getUsersPreferences() {
		return this.usersPreferences;
	}

	public void setUsersPreferences(Set<UsersPreference> usersPreferences) {
		this.usersPreferences = usersPreferences;
	}

}
