package fr.wild.hibernate;

// Generated 10 nov. 2015 15:14:18 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PrivateMessage generated by hbm2java
 */
public class PrivateMessage implements java.io.Serializable {

	private String idMessage;
	private User user;
	private String subject;
	private String contents;
	private Date datePost;
	private Set<ReadPrivateMessage> readPrivateMessages = new HashSet<ReadPrivateMessage>(
			0);

	public PrivateMessage() {
	}

	public PrivateMessage(String idMessage, User user, Date datePost) {
		this.idMessage = idMessage;
		this.user = user;
		this.datePost = datePost;
	}

	public PrivateMessage(String idMessage, User user, String subject,
			String contents, Date datePost,
			Set<ReadPrivateMessage> readPrivateMessages) {
		this.idMessage = idMessage;
		this.user = user;
		this.subject = subject;
		this.contents = contents;
		this.datePost = datePost;
		this.readPrivateMessages = readPrivateMessages;
	}

	public String getIdMessage() {
		return this.idMessage;
	}

	public void setIdMessage(String idMessage) {
		this.idMessage = idMessage;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	public String getContents() {
		return this.contents;
	}

	public void setContents(String contents) {
		this.contents = contents;
	}

	public Date getDatePost() {
		return this.datePost;
	}

	public void setDatePost(Date datePost) {
		this.datePost = datePost;
	}

	public Set<ReadPrivateMessage> getReadPrivateMessages() {
		return this.readPrivateMessages;
	}

	public void setReadPrivateMessages(
			Set<ReadPrivateMessage> readPrivateMessages) {
		this.readPrivateMessages = readPrivateMessages;
	}

}
