package fr.wild.hibernate;

// Generated 10 nov. 2015 15:14:18 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * PublicationLevel generated by hbm2java
 */
public class PublicationLevel implements java.io.Serializable {

	private short idPublicationLevel;
	private String shortName;
	private String fullName;
	private String description;
	private Set<UserFile> userFiles = new HashSet<UserFile>(0);

	public PublicationLevel() {
	}

	public PublicationLevel(short idPublicationLevel, String shortName,
			String fullName) {
		this.idPublicationLevel = idPublicationLevel;
		this.shortName = shortName;
		this.fullName = fullName;
	}

	public PublicationLevel(short idPublicationLevel, String shortName,
			String fullName, String description, Set<UserFile> userFiles) {
		this.idPublicationLevel = idPublicationLevel;
		this.shortName = shortName;
		this.fullName = fullName;
		this.description = description;
		this.userFiles = userFiles;
	}

	public short getIdPublicationLevel() {
		return this.idPublicationLevel;
	}

	public void setIdPublicationLevel(short idPublicationLevel) {
		this.idPublicationLevel = idPublicationLevel;
	}

	public String getShortName() {
		return this.shortName;
	}

	public void setShortName(String shortName) {
		this.shortName = shortName;
	}

	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<UserFile> getUserFiles() {
		return this.userFiles;
	}

	public void setUserFiles(Set<UserFile> userFiles) {
		this.userFiles = userFiles;
	}

}
