package fr.wild.hibernate;

// Generated 10 nov. 2015 15:14:18 by Hibernate Tools 3.4.0.CR1

/**
 * ReadPrivateMessageId generated by hbm2java
 */
public class ReadPrivateMessageId implements java.io.Serializable {

	private String idMessage;
	private String idUserTarget;

	public ReadPrivateMessageId() {
	}

	public ReadPrivateMessageId(String idMessage, String idUserTarget) {
		this.idMessage = idMessage;
		this.idUserTarget = idUserTarget;
	}

	public String getIdMessage() {
		return this.idMessage;
	}

	public void setIdMessage(String idMessage) {
		this.idMessage = idMessage;
	}

	public String getIdUserTarget() {
		return this.idUserTarget;
	}

	public void setIdUserTarget(String idUserTarget) {
		this.idUserTarget = idUserTarget;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ReadPrivateMessageId))
			return false;
		ReadPrivateMessageId castOther = (ReadPrivateMessageId) other;

		return ((this.getIdMessage() == castOther.getIdMessage()) || (this
				.getIdMessage() != null && castOther.getIdMessage() != null && this
				.getIdMessage().equals(castOther.getIdMessage())))
				&& ((this.getIdUserTarget() == castOther.getIdUserTarget()) || (this
						.getIdUserTarget() != null
						&& castOther.getIdUserTarget() != null && this
						.getIdUserTarget().equals(castOther.getIdUserTarget())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getIdMessage() == null ? 0 : this.getIdMessage().hashCode());
		result = 37
				* result
				+ (getIdUserTarget() == null ? 0 : this.getIdUserTarget()
						.hashCode());
		return result;
	}

}
