package fr.wild.hibernate;

// Generated 16 nov. 2015 11:38:05 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * ReferenceConcept generated by hbm2java
 */
public class ReferenceConcept implements java.io.Serializable {

	private String idReferenceTheme;
	private String fullName;
	private String description;
	private Set<ReferenceFile> referenceFiles = new HashSet<ReferenceFile>(0);
	private Set<ReferenceWord> referenceWords = new HashSet<ReferenceWord>(0);

	public ReferenceConcept() {
	}

	public ReferenceConcept(String idReferenceTheme, String fullName) {
		this.idReferenceTheme = idReferenceTheme;
		this.fullName = fullName;
	}

	public ReferenceConcept(String idReferenceTheme, String fullName,
			String description, Set<ReferenceFile> referenceFiles,
			Set<ReferenceWord> referenceWords) {
		this.idReferenceTheme = idReferenceTheme;
		this.fullName = fullName;
		this.description = description;
		this.referenceFiles = referenceFiles;
		this.referenceWords = referenceWords;
	}

	public String getIdReferenceTheme() {
		return this.idReferenceTheme;
	}

	public void setIdReferenceTheme(String idReferenceTheme) {
		this.idReferenceTheme = idReferenceTheme;
	}

	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<ReferenceFile> getReferenceFiles() {
		return this.referenceFiles;
	}

	public void setReferenceFiles(Set<ReferenceFile> referenceFiles) {
		this.referenceFiles = referenceFiles;
	}

	public Set<ReferenceWord> getReferenceWords() {
		return this.referenceWords;
	}

	public void setReferenceWords(Set<ReferenceWord> referenceWords) {
		this.referenceWords = referenceWords;
	}

}
