package fr.wild.hibernate;

// Generated 16 nov. 2015 11:38:05 by Hibernate Tools 3.4.0.CR1

/**
 * ReferenceFileId generated by hbm2java
 */
public class ReferenceFileId implements java.io.Serializable {

	private String idReferenceTheme;
	private String idUserFile;

	public ReferenceFileId() {
	}

	public ReferenceFileId(String idReferenceTheme, String idUserFile) {
		this.idReferenceTheme = idReferenceTheme;
		this.idUserFile = idUserFile;
	}

	public String getIdReferenceTheme() {
		return this.idReferenceTheme;
	}

	public void setIdReferenceTheme(String idReferenceTheme) {
		this.idReferenceTheme = idReferenceTheme;
	}

	public String getIdUserFile() {
		return this.idUserFile;
	}

	public void setIdUserFile(String idUserFile) {
		this.idUserFile = idUserFile;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ReferenceFileId))
			return false;
		ReferenceFileId castOther = (ReferenceFileId) other;

		return ((this.getIdReferenceTheme() == castOther.getIdReferenceTheme()) || (this
				.getIdReferenceTheme() != null
				&& castOther.getIdReferenceTheme() != null && this
				.getIdReferenceTheme().equals(castOther.getIdReferenceTheme())))
				&& ((this.getIdUserFile() == castOther.getIdUserFile()) || (this
						.getIdUserFile() != null
						&& castOther.getIdUserFile() != null && this
						.getIdUserFile().equals(castOther.getIdUserFile())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getIdReferenceTheme() == null ? 0 : this
						.getIdReferenceTheme().hashCode());
		result = 37
				* result
				+ (getIdUserFile() == null ? 0 : this.getIdUserFile()
						.hashCode());
		return result;
	}

}
