package fr.wild.hibernate;

// Generated 16 nov. 2015 11:38:05 by Hibernate Tools 3.4.0.CR1

/**
 * ReferenceWord generated by hbm2java
 */
public class ReferenceWord implements java.io.Serializable {

	private String idReferenceWord;
	private ReferenceConcept referenceConcept;
	private String fullName;
	private String description;

	public ReferenceWord() {
	}

	public ReferenceWord(String idReferenceWord, String fullName) {
		this.idReferenceWord = idReferenceWord;
		this.fullName = fullName;
	}

	public ReferenceWord(String idReferenceWord,
			ReferenceConcept referenceConcept, String fullName,
			String description) {
		this.idReferenceWord = idReferenceWord;
		this.referenceConcept = referenceConcept;
		this.fullName = fullName;
		this.description = description;
	}

	public String getIdReferenceWord() {
		return this.idReferenceWord;
	}

	public void setIdReferenceWord(String idReferenceWord) {
		this.idReferenceWord = idReferenceWord;
	}

	public ReferenceConcept getReferenceConcept() {
		return this.referenceConcept;
	}

	public void setReferenceConcept(ReferenceConcept referenceConcept) {
		this.referenceConcept = referenceConcept;
	}

	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
