package fr.wild.hibernate;

// Generated 10 nov. 2015 15:14:18 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Status generated by hbm2java
 */
public class Status implements java.io.Serializable {

	private short idStatus;
	private String fullName;
	private String description;
	private Set<ExecutionChainsaw> executionChainsaws = new HashSet<ExecutionChainsaw>(
			0);
	private Set<JavaService> javaServices = new HashSet<JavaService>(0);
	private Set<ExecutionList> executionLists = new HashSet<ExecutionList>(0);
	private Set<ExecutionArchive> executionArchives = new HashSet<ExecutionArchive>(
			0);

	public Status() {
	}

	public Status(short idStatus, String fullName) {
		this.idStatus = idStatus;
		this.fullName = fullName;
	}

	public Status(short idStatus, String fullName, String description,
			Set<ExecutionChainsaw> executionChainsaws,
			Set<JavaService> javaServices, Set<ExecutionList> executionLists,
			Set<ExecutionArchive> executionArchives) {
		this.idStatus = idStatus;
		this.fullName = fullName;
		this.description = description;
		this.executionChainsaws = executionChainsaws;
		this.javaServices = javaServices;
		this.executionLists = executionLists;
		this.executionArchives = executionArchives;
	}

	public short getIdStatus() {
		return this.idStatus;
	}

	public void setIdStatus(short idStatus) {
		this.idStatus = idStatus;
	}

	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<ExecutionChainsaw> getExecutionChainsaws() {
		return this.executionChainsaws;
	}

	public void setExecutionChainsaws(Set<ExecutionChainsaw> executionChainsaws) {
		this.executionChainsaws = executionChainsaws;
	}

	public Set<JavaService> getJavaServices() {
		return this.javaServices;
	}

	public void setJavaServices(Set<JavaService> javaServices) {
		this.javaServices = javaServices;
	}

	public Set<ExecutionList> getExecutionLists() {
		return this.executionLists;
	}

	public void setExecutionLists(Set<ExecutionList> executionLists) {
		this.executionLists = executionLists;
	}

	public Set<ExecutionArchive> getExecutionArchives() {
		return this.executionArchives;
	}

	public void setExecutionArchives(Set<ExecutionArchive> executionArchives) {
		this.executionArchives = executionArchives;
	}

}
