package fr.wild.hibernate;

// Generated 10 nov. 2015 15:14:18 by Hibernate Tools 3.4.0.CR1

/**
 * Tag generated by hbm2java
 */
public class Tag implements java.io.Serializable {

	private String tagvalue;

	public Tag() {
	}

	public Tag(String tagvalue) {
		this.tagvalue = tagvalue;
	}

	public String getTagvalue() {
		return this.tagvalue;
	}

	public void setTagvalue(String tagvalue) {
		this.tagvalue = tagvalue;
	}

}
