package fr.wild.hibernate;

// Generated 16 nov. 2015 12:24:47 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;

/**
 * UserConsumptionId generated by hbm2java
 */
public class UserConsumptionId implements java.io.Serializable {

	private String idUser;
	private Long ctExecution;
	private Date minDatePost;
	private Date maxDatePost;
	private Serializable longestWait;
	private Serializable longestExectime;
	private Long maxAllocatedRom;
	private Long maxAllocatedRam;
	private Long maxAllocatedCpu;
	private Long estimatedRom;
	private Long estimatedRam;
	private Long estimatedCpu;

	public UserConsumptionId() {
	}

	public UserConsumptionId(String idUser, Long ctExecution, Date minDatePost,
			Date maxDatePost, Serializable longestWait,
			Serializable longestExectime, Long maxAllocatedRom,
			Long maxAllocatedRam, Long maxAllocatedCpu, Long estimatedRom,
			Long estimatedRam, Long estimatedCpu) {
		this.idUser = idUser;
		this.ctExecution = ctExecution;
		this.minDatePost = minDatePost;
		this.maxDatePost = maxDatePost;
		this.longestWait = longestWait;
		this.longestExectime = longestExectime;
		this.maxAllocatedRom = maxAllocatedRom;
		this.maxAllocatedRam = maxAllocatedRam;
		this.maxAllocatedCpu = maxAllocatedCpu;
		this.estimatedRom = estimatedRom;
		this.estimatedRam = estimatedRam;
		this.estimatedCpu = estimatedCpu;
	}

	public String getIdUser() {
		return this.idUser;
	}

	public void setIdUser(String idUser) {
		this.idUser = idUser;
	}

	public Long getCtExecution() {
		return this.ctExecution;
	}

	public void setCtExecution(Long ctExecution) {
		this.ctExecution = ctExecution;
	}

	public Date getMinDatePost() {
		return this.minDatePost;
	}

	public void setMinDatePost(Date minDatePost) {
		this.minDatePost = minDatePost;
	}

	public Date getMaxDatePost() {
		return this.maxDatePost;
	}

	public void setMaxDatePost(Date maxDatePost) {
		this.maxDatePost = maxDatePost;
	}

	public Serializable getLongestWait() {
		return this.longestWait;
	}

	public void setLongestWait(Serializable longestWait) {
		this.longestWait = longestWait;
	}

	public Serializable getLongestExectime() {
		return this.longestExectime;
	}

	public void setLongestExectime(Serializable longestExectime) {
		this.longestExectime = longestExectime;
	}

	public Long getMaxAllocatedRom() {
		return this.maxAllocatedRom;
	}

	public void setMaxAllocatedRom(Long maxAllocatedRom) {
		this.maxAllocatedRom = maxAllocatedRom;
	}

	public Long getMaxAllocatedRam() {
		return this.maxAllocatedRam;
	}

	public void setMaxAllocatedRam(Long maxAllocatedRam) {
		this.maxAllocatedRam = maxAllocatedRam;
	}

	public Long getMaxAllocatedCpu() {
		return this.maxAllocatedCpu;
	}

	public void setMaxAllocatedCpu(Long maxAllocatedCpu) {
		this.maxAllocatedCpu = maxAllocatedCpu;
	}

	public Long getEstimatedRom() {
		return this.estimatedRom;
	}

	public void setEstimatedRom(Long estimatedRom) {
		this.estimatedRom = estimatedRom;
	}

	public Long getEstimatedRam() {
		return this.estimatedRam;
	}

	public void setEstimatedRam(Long estimatedRam) {
		this.estimatedRam = estimatedRam;
	}

	public Long getEstimatedCpu() {
		return this.estimatedCpu;
	}

	public void setEstimatedCpu(Long estimatedCpu) {
		this.estimatedCpu = estimatedCpu;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserConsumptionId))
			return false;
		UserConsumptionId castOther = (UserConsumptionId) other;

		return ((this.getIdUser() == castOther.getIdUser()) || (this
				.getIdUser() != null && castOther.getIdUser() != null && this
				.getIdUser().equals(castOther.getIdUser())))
				&& ((this.getCtExecution() == castOther.getCtExecution()) || (this
						.getCtExecution() != null
						&& castOther.getCtExecution() != null && this
						.getCtExecution().equals(castOther.getCtExecution())))
				&& ((this.getMinDatePost() == castOther.getMinDatePost()) || (this
						.getMinDatePost() != null
						&& castOther.getMinDatePost() != null && this
						.getMinDatePost().equals(castOther.getMinDatePost())))
				&& ((this.getMaxDatePost() == castOther.getMaxDatePost()) || (this
						.getMaxDatePost() != null
						&& castOther.getMaxDatePost() != null && this
						.getMaxDatePost().equals(castOther.getMaxDatePost())))
				&& ((this.getLongestWait() == castOther.getLongestWait()) || (this
						.getLongestWait() != null
						&& castOther.getLongestWait() != null && this
						.getLongestWait().equals(castOther.getLongestWait())))
				&& ((this.getLongestExectime() == castOther
						.getLongestExectime()) || (this.getLongestExectime() != null
						&& castOther.getLongestExectime() != null && this
						.getLongestExectime().equals(
								castOther.getLongestExectime())))
				&& ((this.getMaxAllocatedRom() == castOther
						.getMaxAllocatedRom()) || (this.getMaxAllocatedRom() != null
						&& castOther.getMaxAllocatedRom() != null && this
						.getMaxAllocatedRom().equals(
								castOther.getMaxAllocatedRom())))
				&& ((this.getMaxAllocatedRam() == castOther
						.getMaxAllocatedRam()) || (this.getMaxAllocatedRam() != null
						&& castOther.getMaxAllocatedRam() != null && this
						.getMaxAllocatedRam().equals(
								castOther.getMaxAllocatedRam())))
				&& ((this.getMaxAllocatedCpu() == castOther
						.getMaxAllocatedCpu()) || (this.getMaxAllocatedCpu() != null
						&& castOther.getMaxAllocatedCpu() != null && this
						.getMaxAllocatedCpu().equals(
								castOther.getMaxAllocatedCpu())))
				&& ((this.getEstimatedRom() == castOther.getEstimatedRom()) || (this
						.getEstimatedRom() != null
						&& castOther.getEstimatedRom() != null && this
						.getEstimatedRom().equals(castOther.getEstimatedRom())))
				&& ((this.getEstimatedRam() == castOther.getEstimatedRam()) || (this
						.getEstimatedRam() != null
						&& castOther.getEstimatedRam() != null && this
						.getEstimatedRam().equals(castOther.getEstimatedRam())))
				&& ((this.getEstimatedCpu() == castOther.getEstimatedCpu()) || (this
						.getEstimatedCpu() != null
						&& castOther.getEstimatedCpu() != null && this
						.getEstimatedCpu().equals(castOther.getEstimatedCpu())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getIdUser() == null ? 0 : this.getIdUser().hashCode());
		result = 37
				* result
				+ (getCtExecution() == null ? 0 : this.getCtExecution()
						.hashCode());
		result = 37
				* result
				+ (getMinDatePost() == null ? 0 : this.getMinDatePost()
						.hashCode());
		result = 37
				* result
				+ (getMaxDatePost() == null ? 0 : this.getMaxDatePost()
						.hashCode());
		result = 37
				* result
				+ (getLongestWait() == null ? 0 : this.getLongestWait()
						.hashCode());
		result = 37
				* result
				+ (getLongestExectime() == null ? 0 : this.getLongestExectime()
						.hashCode());
		result = 37
				* result
				+ (getMaxAllocatedRom() == null ? 0 : this.getMaxAllocatedRom()
						.hashCode());
		result = 37
				* result
				+ (getMaxAllocatedRam() == null ? 0 : this.getMaxAllocatedRam()
						.hashCode());
		result = 37
				* result
				+ (getMaxAllocatedCpu() == null ? 0 : this.getMaxAllocatedCpu()
						.hashCode());
		result = 37
				* result
				+ (getEstimatedRom() == null ? 0 : this.getEstimatedRom()
						.hashCode());
		result = 37
				* result
				+ (getEstimatedRam() == null ? 0 : this.getEstimatedRam()
						.hashCode());
		result = 37
				* result
				+ (getEstimatedCpu() == null ? 0 : this.getEstimatedCpu()
						.hashCode());
		return result;
	}

}
