package fr.wild.hibernate;

// Generated 10 nov. 2015 15:14:18 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * UserFile generated by hbm2java
 */
public class UserFile implements java.io.Serializable {

	private String idUserFile;
	private PublicationLevel publicationLevel;
	private ValidateLevel validateLevel;
	private User user;
	private String nameMetadataFile;
	private String nameUserFile;
	private String lastKnownClass;
	private String ownMetadata;
	private Date dateCreation;
	private Date dateLastModif;
	private Set<CommentFile> commentFiles = new HashSet<CommentFile>(0);

	public UserFile() {
	}

	public UserFile(String idUserFile, PublicationLevel publicationLevel,
			ValidateLevel validateLevel, User user, Date dateCreation) {
		this.idUserFile = idUserFile;
		this.publicationLevel = publicationLevel;
		this.validateLevel = validateLevel;
		this.user = user;
		this.dateCreation = dateCreation;
	}

	public UserFile(String idUserFile, PublicationLevel publicationLevel,
			ValidateLevel validateLevel, User user, String nameMetadataFile,
			String nameUserFile, String lastKnownClass, String ownMetadata,
			Date dateCreation, Date dateLastModif, Set<CommentFile> commentFiles) {
		this.idUserFile = idUserFile;
		this.publicationLevel = publicationLevel;
		this.validateLevel = validateLevel;
		this.user = user;
		this.nameMetadataFile = nameMetadataFile;
		this.nameUserFile = nameUserFile;
		this.lastKnownClass = lastKnownClass;
		this.ownMetadata = ownMetadata;
		this.dateCreation = dateCreation;
		this.dateLastModif = dateLastModif;
		this.commentFiles = commentFiles;
	}

	public String getIdUserFile() {
		return this.idUserFile;
	}

	public void setIdUserFile(String idUserFile) {
		this.idUserFile = idUserFile;
	}

	public PublicationLevel getPublicationLevel() {
		return this.publicationLevel;
	}

	public void setPublicationLevel(PublicationLevel publicationLevel) {
		this.publicationLevel = publicationLevel;
	}

	public ValidateLevel getValidateLevel() {
		return this.validateLevel;
	}

	public void setValidateLevel(ValidateLevel validateLevel) {
		this.validateLevel = validateLevel;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getNameMetadataFile() {
		return this.nameMetadataFile;
	}

	public void setNameMetadataFile(String nameMetadataFile) {
		this.nameMetadataFile = nameMetadataFile;
	}

	public String getNameUserFile() {
		return this.nameUserFile;
	}

	public void setNameUserFile(String nameUserFile) {
		this.nameUserFile = nameUserFile;
	}

	public String getLastKnownClass() {
		return this.lastKnownClass;
	}

	public void setLastKnownClass(String lastKnownClass) {
		this.lastKnownClass = lastKnownClass;
	}

	public String getOwnMetadata() {
		return this.ownMetadata;
	}

	public void setOwnMetadata(String ownMetadata) {
		this.ownMetadata = ownMetadata;
	}

	public Date getDateCreation() {
		return this.dateCreation;
	}

	public void setDateCreation(Date dateCreation) {
		this.dateCreation = dateCreation;
	}

	public Date getDateLastModif() {
		return this.dateLastModif;
	}

	public void setDateLastModif(Date dateLastModif) {
		this.dateLastModif = dateLastModif;
	}

	public Set<CommentFile> getCommentFiles() {
		return this.commentFiles;
	}

	public void setCommentFiles(Set<CommentFile> commentFiles) {
		this.commentFiles = commentFiles;
	}

}
