package fr.wild.hibernate;

// Generated 10 nov. 2015 15:14:18 by Hibernate Tools 3.4.0.CR1

/**
 * UsersPreferenceId generated by hbm2java
 */
public class UsersPreferenceId implements java.io.Serializable {

	private String idUser;
	private int idPreference;

	public UsersPreferenceId() {
	}

	public UsersPreferenceId(String idUser, int idPreference) {
		this.idUser = idUser;
		this.idPreference = idPreference;
	}

	public String getIdUser() {
		return this.idUser;
	}

	public void setIdUser(String idUser) {
		this.idUser = idUser;
	}

	public int getIdPreference() {
		return this.idPreference;
	}

	public void setIdPreference(int idPreference) {
		this.idPreference = idPreference;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsersPreferenceId))
			return false;
		UsersPreferenceId castOther = (UsersPreferenceId) other;

		return ((this.getIdUser() == castOther.getIdUser()) || (this
				.getIdUser() != null && castOther.getIdUser() != null && this
				.getIdUser().equals(castOther.getIdUser())))
				&& (this.getIdPreference() == castOther.getIdPreference());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getIdUser() == null ? 0 : this.getIdUser().hashCode());
		result = 37 * result + this.getIdPreference();
		return result;
	}

}
