package fr.wild.hibernate;

// Generated 10 nov. 2015 15:14:01 by Hibernate Tools 3.4.0.CR1

/**
 * UserConsumption generated by hbm2java
 */
public class UserConsumption implements java.io.Serializable {

	private UserConsumptionId id;

	public UserConsumption() {
	}

	public UserConsumption(UserConsumptionId id) {
		this.id = id;
	}

	public UserConsumptionId getId() {
		return this.id;
	}

	public void setId(UserConsumptionId id) {
		this.id = id;
	}

}
