package fr.wild.hibernate;

// Generated 10 nov. 2015 15:14:18 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private String idUser;
	private AdminLevel adminLevel;
	private String userName;
	private String userForname;
	private String userMail;
	private boolean activatedAccount;
	private Date dateCreation;
	private Date dateLastConnection;
	private Date dateFirstConnection;
	private Date dateUpdateConnection;
	private String userPassword;
	private Integer sandreServiceId;
	private Set<ExecutionChainsaw> executionChainsaws = new HashSet<ExecutionChainsaw>(
			0);
	private Set<River> riversForIdUserCreator = new HashSet<River>(0);
	private Set<Drop> drops = new HashSet<Drop>(0);
	private Set<ReadPrivateMessage> readPrivateMessages = new HashSet<ReadPrivateMessage>(
			0);
	private Set<CommentDrop> commentDrops = new HashSet<CommentDrop>(0);
	private Set<AdminLevel> adminLevels = new HashSet<AdminLevel>(0);
	private Set<ExecutionArchive> executionArchives = new HashSet<ExecutionArchive>(
			0);
	private Set<Project> projectsForIdUserAdmin = new HashSet<Project>(0);
	private Set<CommentFile> commentFiles = new HashSet<CommentFile>(0);
	private Set<UsersPreference> usersPreferences = new HashSet<UsersPreference>(
			0);
	private Set<AdminLevel> adminLevels_1 = new HashSet<AdminLevel>(0);
	private Set<PrivateMessage> privateMessages = new HashSet<PrivateMessage>(0);
	private Set<Project> projectsForIdUserCreator = new HashSet<Project>(0);
	private Set<JavaService> javaServices = new HashSet<JavaService>(0);
	private Set<ExecutionList> executionLists = new HashSet<ExecutionList>(0);
	private Set<River> riversForIdUserAdmin = new HashSet<River>(0);
	private Set<UserFile> userFiles = new HashSet<UserFile>(0);

	public User() {
	}

	public User(String idUser, AdminLevel adminLevel, String userName,
			String userForname, String userMail, boolean activatedAccount,
			Date dateCreation) {
		this.idUser = idUser;
		this.adminLevel = adminLevel;
		this.userName = userName;
		this.userForname = userForname;
		this.userMail = userMail;
		this.activatedAccount = activatedAccount;
		this.dateCreation = dateCreation;
	}

	public User(String idUser, AdminLevel adminLevel, String userName,
			String userForname, String userMail, boolean activatedAccount,
			Date dateCreation, Date dateLastConnection,
			Date dateFirstConnection, Date dateUpdateConnection,
			String userPassword, Integer sandreServiceId,
			Set<ExecutionChainsaw> executionChainsaws,
			Set<River> riversForIdUserCreator, Set<Drop> drops,
			Set<ReadPrivateMessage> readPrivateMessages,
			Set<CommentDrop> commentDrops, Set<AdminLevel> adminLevels,
			Set<ExecutionArchive> executionArchives,
			Set<Project> projectsForIdUserAdmin, Set<CommentFile> commentFiles,
			Set<UsersPreference> usersPreferences,
			Set<AdminLevel> adminLevels_1, Set<PrivateMessage> privateMessages,
			Set<Project> projectsForIdUserCreator,
			Set<JavaService> javaServices, Set<ExecutionList> executionLists,
			Set<River> riversForIdUserAdmin, Set<UserFile> userFiles) {
		this.idUser = idUser;
		this.adminLevel = adminLevel;
		this.userName = userName;
		this.userForname = userForname;
		this.userMail = userMail;
		this.activatedAccount = activatedAccount;
		this.dateCreation = dateCreation;
		this.dateLastConnection = dateLastConnection;
		this.dateFirstConnection = dateFirstConnection;
		this.dateUpdateConnection = dateUpdateConnection;
		this.userPassword = userPassword;
		this.sandreServiceId = sandreServiceId;
		this.executionChainsaws = executionChainsaws;
		this.riversForIdUserCreator = riversForIdUserCreator;
		this.drops = drops;
		this.readPrivateMessages = readPrivateMessages;
		this.commentDrops = commentDrops;
		this.adminLevels = adminLevels;
		this.executionArchives = executionArchives;
		this.projectsForIdUserAdmin = projectsForIdUserAdmin;
		this.commentFiles = commentFiles;
		this.usersPreferences = usersPreferences;
		this.adminLevels_1 = adminLevels_1;
		this.privateMessages = privateMessages;
		this.projectsForIdUserCreator = projectsForIdUserCreator;
		this.javaServices = javaServices;
		this.executionLists = executionLists;
		this.riversForIdUserAdmin = riversForIdUserAdmin;
		this.userFiles = userFiles;
	}

	public String getIdUser() {
		return this.idUser;
	}

	public void setIdUser(String idUser) {
		this.idUser = idUser;
	}

	public AdminLevel getAdminLevel() {
		return this.adminLevel;
	}

	public void setAdminLevel(AdminLevel adminLevel) {
		this.adminLevel = adminLevel;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getUserForname() {
		return this.userForname;
	}

	public void setUserForname(String userForname) {
		this.userForname = userForname;
	}

	public String getUserMail() {
		return this.userMail;
	}

	public void setUserMail(String userMail) {
		this.userMail = userMail;
	}

	public boolean isActivatedAccount() {
		return this.activatedAccount;
	}

	public void setActivatedAccount(boolean activatedAccount) {
		this.activatedAccount = activatedAccount;
	}

	public Date getDateCreation() {
		return this.dateCreation;
	}

	public void setDateCreation(Date dateCreation) {
		this.dateCreation = dateCreation;
	}

	public Date getDateLastConnection() {
		return this.dateLastConnection;
	}

	public void setDateLastConnection(Date dateLastConnection) {
		this.dateLastConnection = dateLastConnection;
	}

	public Date getDateFirstConnection() {
		return this.dateFirstConnection;
	}

	public void setDateFirstConnection(Date dateFirstConnection) {
		this.dateFirstConnection = dateFirstConnection;
	}

	public Date getDateUpdateConnection() {
		return this.dateUpdateConnection;
	}

	public void setDateUpdateConnection(Date dateUpdateConnection) {
		this.dateUpdateConnection = dateUpdateConnection;
	}

	public String getUserPassword() {
		return this.userPassword;
	}

	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	public Integer getSandreServiceId() {
		return this.sandreServiceId;
	}

	public void setSandreServiceId(Integer sandreServiceId) {
		this.sandreServiceId = sandreServiceId;
	}

	public Set<ExecutionChainsaw> getExecutionChainsaws() {
		return this.executionChainsaws;
	}

	public void setExecutionChainsaws(Set<ExecutionChainsaw> executionChainsaws) {
		this.executionChainsaws = executionChainsaws;
	}

	public Set<River> getRiversForIdUserCreator() {
		return this.riversForIdUserCreator;
	}

	public void setRiversForIdUserCreator(Set<River> riversForIdUserCreator) {
		this.riversForIdUserCreator = riversForIdUserCreator;
	}

	public Set<Drop> getDrops() {
		return this.drops;
	}

	public void setDrops(Set<Drop> drops) {
		this.drops = drops;
	}

	public Set<ReadPrivateMessage> getReadPrivateMessages() {
		return this.readPrivateMessages;
	}

	public void setReadPrivateMessages(
			Set<ReadPrivateMessage> readPrivateMessages) {
		this.readPrivateMessages = readPrivateMessages;
	}

	public Set<CommentDrop> getCommentDrops() {
		return this.commentDrops;
	}

	public void setCommentDrops(Set<CommentDrop> commentDrops) {
		this.commentDrops = commentDrops;
	}

	public Set<AdminLevel> getAdminLevels() {
		return this.adminLevels;
	}

	public void setAdminLevels(Set<AdminLevel> adminLevels) {
		this.adminLevels = adminLevels;
	}

	public Set<ExecutionArchive> getExecutionArchives() {
		return this.executionArchives;
	}

	public void setExecutionArchives(Set<ExecutionArchive> executionArchives) {
		this.executionArchives = executionArchives;
	}

	public Set<Project> getProjectsForIdUserAdmin() {
		return this.projectsForIdUserAdmin;
	}

	public void setProjectsForIdUserAdmin(Set<Project> projectsForIdUserAdmin) {
		this.projectsForIdUserAdmin = projectsForIdUserAdmin;
	}

	public Set<CommentFile> getCommentFiles() {
		return this.commentFiles;
	}

	public void setCommentFiles(Set<CommentFile> commentFiles) {
		this.commentFiles = commentFiles;
	}

	public Set<UsersPreference> getUsersPreferences() {
		return this.usersPreferences;
	}

	public void setUsersPreferences(Set<UsersPreference> usersPreferences) {
		this.usersPreferences = usersPreferences;
	}

	public Set<AdminLevel> getAdminLevels_1() {
		return this.adminLevels_1;
	}

	public void setAdminLevels_1(Set<AdminLevel> adminLevels_1) {
		this.adminLevels_1 = adminLevels_1;
	}

	public Set<PrivateMessage> getPrivateMessages() {
		return this.privateMessages;
	}

	public void setPrivateMessages(Set<PrivateMessage> privateMessages) {
		this.privateMessages = privateMessages;
	}

	public Set<Project> getProjectsForIdUserCreator() {
		return this.projectsForIdUserCreator;
	}

	public void setProjectsForIdUserCreator(
			Set<Project> projectsForIdUserCreator) {
		this.projectsForIdUserCreator = projectsForIdUserCreator;
	}

	public Set<JavaService> getJavaServices() {
		return this.javaServices;
	}

	public void setJavaServices(Set<JavaService> javaServices) {
		this.javaServices = javaServices;
	}

	public Set<ExecutionList> getExecutionLists() {
		return this.executionLists;
	}

	public void setExecutionLists(Set<ExecutionList> executionLists) {
		this.executionLists = executionLists;
	}

	public Set<River> getRiversForIdUserAdmin() {
		return this.riversForIdUserAdmin;
	}

	public void setRiversForIdUserAdmin(Set<River> riversForIdUserAdmin) {
		this.riversForIdUserAdmin = riversForIdUserAdmin;
	}

	public Set<UserFile> getUserFiles() {
		return this.userFiles;
	}

	public void setUserFiles(Set<UserFile> userFiles) {
		this.userFiles = userFiles;
	}

}
