package fr.wild.hibernate;

// Generated 10 nov. 2015 15:14:18 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * VarType generated by hbm2java
 */
public class VarType implements java.io.Serializable {

	private int idVarType;
	private String diceType;
	private String pgType;
	private String javaType;
	private Set<Preference> preferences = new HashSet<Preference>(0);

	public VarType() {
	}

	public VarType(int idVarType, String diceType, String pgType,
			String javaType) {
		this.idVarType = idVarType;
		this.diceType = diceType;
		this.pgType = pgType;
		this.javaType = javaType;
	}

	public VarType(int idVarType, String diceType, String pgType,
			String javaType, Set<Preference> preferences) {
		this.idVarType = idVarType;
		this.diceType = diceType;
		this.pgType = pgType;
		this.javaType = javaType;
		this.preferences = preferences;
	}

	public int getIdVarType() {
		return this.idVarType;
	}

	public void setIdVarType(int idVarType) {
		this.idVarType = idVarType;
	}

	public String getDiceType() {
		return this.diceType;
	}

	public void setDiceType(String diceType) {
		this.diceType = diceType;
	}

	public String getPgType() {
		return this.pgType;
	}

	public void setPgType(String pgType) {
		this.pgType = pgType;
	}

	public String getJavaType() {
		return this.javaType;
	}

	public void setJavaType(String javaType) {
		this.javaType = javaType;
	}

	public Set<Preference> getPreferences() {
		return this.preferences;
	}

	public void setPreferences(Set<Preference> preferences) {
		this.preferences = preferences;
	}

}
